[2023-12-19T11:40:57.103+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: piper_dags.run_spark_script scheduled__2023-12-11T00:06:00+00:00 [queued]>
[2023-12-19T11:40:57.110+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: piper_dags.run_spark_script scheduled__2023-12-11T00:06:00+00:00 [queued]>
[2023-12-19T11:40:57.110+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-19T11:40:57.128+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): run_spark_script> on 2023-12-11 00:06:00+00:00
[2023-12-19T11:40:57.133+0000] {standard_task_runner.py:60} INFO - Started process 660 to run task
[2023-12-19T11:40:57.135+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'piper_dags', 'run_spark_script', 'scheduled__2023-12-11T00:06:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_dag.py', '--cfg-path', '/tmp/tmp5bsrfrtj']
[2023-12-19T11:40:57.136+0000] {standard_task_runner.py:88} INFO - Job 80: Subtask run_spark_script
[2023-12-19T11:40:57.175+0000] {task_command.py:423} INFO - Running <TaskInstance: piper_dags.run_spark_script scheduled__2023-12-11T00:06:00+00:00 [running]> on host ea216ca38749
[2023-12-19T11:40:57.222+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='limoo' AIRFLOW_CTX_DAG_ID='piper_dags' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T00:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T00:06:00+00:00'
[2023-12-19T11:40:57.335+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spark_job.py", line 5, in run_spark_script
    spark = SparkSession.builder \
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2023-12-19T11:40:57.342+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=piper_dags, task_id=run_spark_script, execution_date=20231211T000600, start_date=20231219T114057, end_date=20231219T114057
[2023-12-19T11:40:57.352+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 80 for task run_spark_script ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 660)
[2023-12-19T11:40:57.387+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-19T11:40:57.424+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
