[2023-12-19T11:56:41.908+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:36:00+00:00 [queued]>
[2023-12-19T11:56:41.918+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:36:00+00:00 [queued]>
[2023-12-19T11:56:41.918+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-19T11:56:42.107+0000] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): run_spark_script> on 2023-12-11 00:36:00+00:00
[2023-12-19T11:56:42.115+0000] {standard_task_runner.py:60} INFO - Started process 1602 to run task
[2023-12-19T11:56:42.118+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spark_dag', 'run_spark_script', 'scheduled__2023-12-11T00:36:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_dag.py', '--cfg-path', '/tmp/tmpb2y_cgc9']
[2023-12-19T11:56:42.120+0000] {standard_task_runner.py:88} INFO - Job 139: Subtask run_spark_script
[2023-12-19T11:56:42.277+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:36:00+00:00 [running]> on host ea216ca38749
[2023-12-19T11:56:42.443+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='limoo' AIRFLOW_CTX_DAG_ID='spark_dag' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T00:36:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T00:36:00+00:00'
[2023-12-19T11:56:42.452+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2023-12-19T11:56:42.453+0000] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master spark://master:4040 --name arrow-spark ./spark_job.py
[2023-12-19T11:56:42.508+0000] {spark_submit.py:521} INFO - /home/***/.local/lib/python3.8/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-12-19T11:56:42.509+0000] {spark_submit.py:521} INFO - JAVA_HOME is not set
[2023-12-19T11:56:42.542+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 160, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://master:4040 --name arrow-spark ./spark_job.py. Error code is: 1.
[2023-12-19T11:56:42.548+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_dag, task_id=run_spark_script, execution_date=20231211T003600, start_date=20231219T115641, end_date=20231219T115642
[2023-12-19T11:56:42.584+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 139 for task run_spark_script (Cannot execute: spark-submit --master spark://master:4040 --name arrow-spark ./spark_job.py. Error code is: 1.; 1602)
[2023-12-19T11:56:42.621+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-19T11:56:42.665+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-20T08:21:51.132+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:36:00+00:00 [queued]>
[2023-12-20T08:21:51.145+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:36:00+00:00 [queued]>
[2023-12-20T08:21:51.146+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-20T08:21:51.284+0000] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): run_spark_script> on 2023-12-11 00:36:00+00:00
[2023-12-20T08:21:51.290+0000] {standard_task_runner.py:60} INFO - Started process 1313 to run task
[2023-12-20T08:21:51.294+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spark_dag', 'run_spark_script', 'scheduled__2023-12-11T00:36:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_dag.py', '--cfg-path', '/tmp/tmpsihnzfx8']
[2023-12-20T08:21:51.296+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask run_spark_script
[2023-12-20T08:21:51.365+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:36:00+00:00 [running]> on host 50ed5d27a03b
[2023-12-20T08:21:51.485+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='limoo' AIRFLOW_CTX_DAG_ID='spark_dag' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T00:36:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T00:36:00+00:00'
[2023-12-20T08:21:51.499+0000] {spark_submit.py:223} INFO - Could not load connection string spark_default, defaulting to yarn
[2023-12-20T08:21:51.502+0000] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark ./spark_job.py
[2023-12-20T08:21:55.190+0000] {spark_submit.py:521} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-12-20T08:21:55.193+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2023-12-20T08:21:55.194+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2023-12-20T08:21:55.194+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2023-12-20T08:21:55.195+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2023-12-20T08:21:55.196+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2023-12-20T08:21:55.197+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2023-12-20T08:21:55.198+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2023-12-20T08:21:55.198+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2023-12-20T08:21:55.200+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2023-12-20T08:21:55.202+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-12-20T08:21:55.234+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 160, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark ./spark_job.py. Error code is: 1.
[2023-12-20T08:21:55.238+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_dag, task_id=run_spark_script, execution_date=20231211T003600, start_date=20231220T082151, end_date=20231220T082155
[2023-12-20T08:21:55.251+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task run_spark_script (Cannot execute: spark-submit --master yarn --name arrow-spark ./spark_job.py. Error code is: 1.; 1313)
[2023-12-20T08:21:55.276+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-20T08:21:55.311+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-20T10:01:17.128+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:36:00+00:00 [queued]>
[2023-12-20T10:01:17.140+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:36:00+00:00 [queued]>
[2023-12-20T10:01:17.141+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-20T10:01:17.280+0000] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): run_spark_script> on 2023-12-11 00:36:00+00:00
[2023-12-20T10:01:17.286+0000] {standard_task_runner.py:60} INFO - Started process 927 to run task
[2023-12-20T10:01:17.290+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spark_dag', 'run_spark_script', 'scheduled__2023-12-11T00:36:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_dag.py', '--cfg-path', '/tmp/tmp57_csx90']
[2023-12-20T10:01:17.295+0000] {standard_task_runner.py:88} INFO - Job 51: Subtask run_spark_script
[2023-12-20T10:01:17.402+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:36:00+00:00 [running]> on host 528c26b638c7
[2023-12-20T10:01:17.552+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='limoo' AIRFLOW_CTX_DAG_ID='spark_dag' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T00:36:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T00:36:00+00:00'
[2023-12-20T10:01:17.572+0000] {spark_submit.py:223} INFO - Could not load connection string spark_default, defaulting to yarn
[2023-12-20T10:01:17.573+0000] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark ./spark_job.py
[2023-12-20T10:01:21.442+0000] {spark_submit.py:521} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-12-20T10:01:21.445+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2023-12-20T10:01:21.446+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2023-12-20T10:01:21.446+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2023-12-20T10:01:21.446+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2023-12-20T10:01:21.446+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2023-12-20T10:01:21.446+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2023-12-20T10:01:21.446+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2023-12-20T10:01:21.446+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2023-12-20T10:01:21.446+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2023-12-20T10:01:21.447+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-12-20T10:01:21.492+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 160, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark ./spark_job.py. Error code is: 1.
[2023-12-20T10:01:21.497+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_dag, task_id=run_spark_script, execution_date=20231211T003600, start_date=20231220T100117, end_date=20231220T100121
[2023-12-20T10:01:21.514+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 51 for task run_spark_script (Cannot execute: spark-submit --master yarn --name arrow-spark ./spark_job.py. Error code is: 1.; 927)
[2023-12-20T10:01:21.542+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-20T10:01:21.566+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
