[2023-12-19T11:56:39.336+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:00:00+00:00 [queued]>
[2023-12-19T11:56:39.358+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:00:00+00:00 [queued]>
[2023-12-19T11:56:39.359+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-19T11:56:39.385+0000] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): run_spark_script> on 2023-12-11 00:00:00+00:00
[2023-12-19T11:56:39.391+0000] {standard_task_runner.py:60} INFO - Started process 1489 to run task
[2023-12-19T11:56:39.398+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spark_dag', 'run_spark_script', 'scheduled__2023-12-11T00:00:00+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_dag.py', '--cfg-path', '/tmp/tmptihbsbm4']
[2023-12-19T11:56:39.400+0000] {standard_task_runner.py:88} INFO - Job 127: Subtask run_spark_script
[2023-12-19T11:56:39.464+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:00:00+00:00 [running]> on host ea216ca38749
[2023-12-19T11:56:39.576+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='limoo' AIRFLOW_CTX_DAG_ID='spark_dag' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T00:00:00+00:00'
[2023-12-19T11:56:39.600+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2023-12-19T11:56:39.606+0000] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master spark://master:4040 --name arrow-spark ./spark_job.py
[2023-12-19T11:56:39.701+0000] {spark_submit.py:521} INFO - /home/***/.local/lib/python3.8/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-12-19T11:56:39.704+0000] {spark_submit.py:521} INFO - JAVA_HOME is not set
[2023-12-19T11:56:39.723+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 160, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://master:4040 --name arrow-spark ./spark_job.py. Error code is: 1.
[2023-12-19T11:56:39.746+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_dag, task_id=run_spark_script, execution_date=20231211T000000, start_date=20231219T115639, end_date=20231219T115639
[2023-12-19T11:56:39.786+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 127 for task run_spark_script (Cannot execute: spark-submit --master spark://master:4040 --name arrow-spark ./spark_job.py. Error code is: 1.; 1489)
[2023-12-19T11:56:39.810+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-19T11:56:39.830+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-20T08:21:49.700+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:00:00+00:00 [queued]>
[2023-12-20T08:21:49.710+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:00:00+00:00 [queued]>
[2023-12-20T08:21:49.711+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-20T08:21:49.733+0000] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): run_spark_script> on 2023-12-11 00:00:00+00:00
[2023-12-20T08:21:49.737+0000] {standard_task_runner.py:60} INFO - Started process 679 to run task
[2023-12-20T08:21:49.739+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spark_dag', 'run_spark_script', 'scheduled__2023-12-11T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_dag.py', '--cfg-path', '/tmp/tmppg6qzhof']
[2023-12-20T08:21:49.741+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask run_spark_script
[2023-12-20T08:21:49.778+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:00:00+00:00 [running]> on host 50ed5d27a03b
[2023-12-20T08:21:49.852+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='limoo' AIRFLOW_CTX_DAG_ID='spark_dag' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T00:00:00+00:00'
[2023-12-20T08:21:49.859+0000] {spark_submit.py:223} INFO - Could not load connection string spark_default, defaulting to yarn
[2023-12-20T08:21:49.860+0000] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark ./spark_job.py
[2023-12-20T08:21:52.937+0000] {spark_submit.py:521} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-12-20T08:21:52.938+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2023-12-20T08:21:52.939+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2023-12-20T08:21:52.939+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2023-12-20T08:21:52.939+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2023-12-20T08:21:52.939+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2023-12-20T08:21:52.939+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2023-12-20T08:21:52.939+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2023-12-20T08:21:52.939+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2023-12-20T08:21:52.939+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2023-12-20T08:21:52.939+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-12-20T08:21:53.003+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 160, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark ./spark_job.py. Error code is: 1.
[2023-12-20T08:21:53.008+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_dag, task_id=run_spark_script, execution_date=20231211T000000, start_date=20231220T082149, end_date=20231220T082153
[2023-12-20T08:21:53.039+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task run_spark_script (Cannot execute: spark-submit --master yarn --name arrow-spark ./spark_job.py. Error code is: 1.; 679)
[2023-12-20T08:21:53.107+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-20T08:21:53.130+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-20T10:01:15.738+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:00:00+00:00 [queued]>
[2023-12-20T10:01:15.754+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:00:00+00:00 [queued]>
[2023-12-20T10:01:15.754+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-20T10:01:15.774+0000] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): run_spark_script> on 2023-12-11 00:00:00+00:00
[2023-12-20T10:01:15.778+0000] {standard_task_runner.py:60} INFO - Started process 331 to run task
[2023-12-20T10:01:15.780+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spark_dag', 'run_spark_script', 'scheduled__2023-12-11T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_dag.py', '--cfg-path', '/tmp/tmpmj38qhz0']
[2023-12-20T10:01:15.781+0000] {standard_task_runner.py:88} INFO - Job 39: Subtask run_spark_script
[2023-12-20T10:01:15.818+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_dag.run_spark_script scheduled__2023-12-11T00:00:00+00:00 [running]> on host 528c26b638c7
[2023-12-20T10:01:15.882+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='limoo' AIRFLOW_CTX_DAG_ID='spark_dag' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T00:00:00+00:00'
[2023-12-20T10:01:15.891+0000] {spark_submit.py:223} INFO - Could not load connection string spark_default, defaulting to yarn
[2023-12-20T10:01:15.892+0000] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark ./spark_job.py
[2023-12-20T10:01:18.599+0000] {spark_submit.py:521} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-12-20T10:01:18.600+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2023-12-20T10:01:18.600+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2023-12-20T10:01:18.600+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2023-12-20T10:01:18.601+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2023-12-20T10:01:18.601+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2023-12-20T10:01:18.601+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2023-12-20T10:01:18.601+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2023-12-20T10:01:18.601+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2023-12-20T10:01:18.601+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2023-12-20T10:01:18.602+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-12-20T10:01:18.661+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 160, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark ./spark_job.py. Error code is: 1.
[2023-12-20T10:01:18.666+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_dag, task_id=run_spark_script, execution_date=20231211T000000, start_date=20231220T100115, end_date=20231220T100118
[2023-12-20T10:01:18.690+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 39 for task run_spark_script (Cannot execute: spark-submit --master yarn --name arrow-spark ./spark_job.py. Error code is: 1.; 331)
[2023-12-20T10:01:18.711+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-20T10:01:18.739+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
